services:
  app:
    image: your_image:your_version 
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    container_name: telnet_automation_system
    environment:
      - DB_DRIVER_POSTGRES=postgresql+psycopg2
      - DB_USER_POSTGRES=your_user
      - DB_PASSWORD_POSTGRES=your_password
      - DB_HOST_POSTGRES=postgres
      - DB_PORT_POSTGRES=5432
      - DB_NAME_POSTGRES=postgres
    ports:
      - "8000:8000"
    env_file:
      - ./docker/.env
    volumes:
      - .:/app
    
  postgres:
    image: postgres:15
    container_name: database_system
    restart: always
    env_file:
      - ./docker/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
